#默认的启动方式 dev
spring:
  cloud:
    config:
      uri: http://localhost:8888/  #路径有问题会报错 最好直接复制浏览器的路径过来
      name: web-admin-feign   #云端配置文件的名字
      label: master
      profile: dev   #开发阶段的profile(测试阶段test,发布阶段：prod)





