spring:
  application:
    name: hello-spring-cloud-service-admin   #服务提供者
  #被zipkin追踪加的配置
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/